version: "3"

services:

  mysql:
    image: "mysql:5.7"
    container_name: demo_mysql
    hostname: demo_mysql
    restart: always
    networks:
      - network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      
  app:
    image: "pl/twyszomirski/demo-app.docker.image:0.0.1"
    container_name: demo_app
    hostname: demo_app
    depends_on:
      - mysql
    restart: always
    networks:
      - network
    ports:
      - "8080:8080"
    command: ["./wait-for.sh", "demo_mysql:3306", "--", "java","-Djava.security.egd=file:/dev/./urandom","-jar","/demo-app.jar"]
   
networks:
  network:
    driver: bridge
